name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
    strategy:
      matrix:
        emacs_version: ['27.1', '28.1', 'snapshot']
    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@v6.0
      with:
        version: ${{ matrix.emacs_version }}
    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        eldev --trace --color=always compile --warnings-as-errors
        eldev --loading=built-source --trace --color=always test --undercover codecov,dontsend
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
